CREATE TABLE "PROTELDBNEW"."QCROLE" (
    "ROLE_ID" CHAR(36 OCTETS) NOT NULL,
    "ROLE_TP" INTEGER NOT NULL WITH DEFAULT,
    "ROLE_NM" VARCHAR(50 OCTETS) NOT NULL,
    "DESCRIPTION" VARCHAR(100 OCTETS),
    "UPD_DT" TIMESTAMP NOT NULL WITH DEFAULT,
    "UPD_UID" VARCHAR(30 OCTETS) NOT NULL WITH DEFAULT 'SYSTEM',
    "UPD_SRC" VARCHAR(20 OCTETS)
) IN "IBMDB2SAMPLEREL";