CREATE TABLE "PROTELDBNEW"."QCFIELDROLE" (
    "ROLE_ID" CHAR(36 OCTETS) NOT NULL,
    "FIELD_ID" CHAR(36 OCTETS) NOT NULL,
    "UPD_DT" TIMESTAMP NOT NULL WITH DEFAULT,
    "UPD_UID" VARCHAR(30 OCTETS) NOT NULL WITH DEFAULT 'SYSTEM',
    "UPD_SRC" VARCHAR(20 OCTETS)
) IN "IBMDB2SAMPLEREL";